const List = [
  {
    name: 'List Of Countries',
    techs: ['react', 'styled components'],
    demo: 'https://georgekvr.github.io/',
    code: 'https://github.com/GeorgeKVR/Countries/tree/main/src',
    image: require('../../images/projects/Countries.png'),
  },
  {
    name: 'Covid-19 Tracker',
    techs: ['html', 'sass', 'javascript'],
    demo: 'https://georgekvr.github.io/Covid-19-Tracker/',
    code: 'https://github.com/GeorgeKVR/Covid-19-Tracker/',
    image: require('../../images/projects/Covid-Tracker.png'),
  },
  {
    name: 'Virtual Keyboard',
    techs: ['html', 'css', 'javascript'],
    demo: 'https://georgekvr.github.io/Virtual-Keyboard/',
    code: 'https://github.com/GeorgeKVR/Virtual-Keyboard/',
    image: require('../../images/projects/virtual-keyboard.png'),
  },
  {
    name: 'Country Quizz',
    techs: ['react', 'css'],
    demo: 'https://georgekvr.github.io/Country-Quizz/',
    code: 'https://github.com/GeorgeKVR/Country-Quizz/tree/main/src',
    image: require('../../images/projects/Country-Quizz.png'),
  },
  {
    name: 'Arbeitnow Jobs',
    techs: ['react', 'css'],
    demo: 'https://georgekvr.github.io/',
    code: 'https://github.com/GeorgeKVR/Arbeitnow-Jobs/tree/main/src',
    image: require('../../images/projects/joblanding.png'),
  },
  {
    name: 'Windbnb',
    techs: ['react', 'css'],
    demo: 'https://georgekvr.github.io/Windbnb/',
    code: 'https://github.com/GeorgeKVR/Windbnb/tree/main/src',
    image: require('../../images/projects/Windbnb.png'),
  },
  {
    name: 'Space Tourism',
    techs: ['react', 'sass'],
    demo: 'https://georgekvr.github.io/Space-Tourism/',
    code: 'https://github.com/GeorgeKVR/Space-Tourism/tree/main/src',
    image: require('../../images/projects/space-tourism.png'),
  },
  {
    name: 'Simple Todo',
    techs: ['htmls', 'sass', 'javascript'],
    demo: 'https://georgekvr.github.io/Simple-Todo/',
    code: 'https://github.com/GeorgeKVR/Simple-Todo/',
    image: require('../../images/projects/Todo.png'),
  },
  {
    name: 'Pomodoro',
    techs: ['html', 'sass', 'javascript'],
    demo: 'https://georgekvr.github.io/25-5-Clock/',
    code: 'https://github.com/GeorgeKVR/25-5-Clock/',
    image: require('../../images/projects/Js-calculator.png'),
  },
  {
    name: 'Drumpad',
    techs: ['html', 'sass', 'javascript'],
    demo: 'https://georgekvr.github.io/Drum-Machine/',
    code: 'https://github.com/GeorgeKVR/Drum-Machine/',
    image: require('../../images/projects/drum-machine.png'),
  },
  {
    name: 'Markdown Previewer',
    techs: ['html', 'sass', 'javascript'],
    demo: 'https://georgekvr.github.io/Markdown-Previewer/',
    code: 'https://github.com/GeorgeKVR/Markdown-Previewer',
    image: require('../../images/projects/Markdown-previewer.png'),
  },
];

export default List;
